### ISSUE TITLE
can't connect if ioBroker is run in Docker

### ISSUE THREAD

**Issue by Schorlewalker** [StrathCole/ioBroker.rainbird#1]
that's the log:
`

host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at main (/opt/iobroker/node_modules/iobroker.rainbird/main.js:124:2)
-- | -- | -- | --
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at pollStates (/opt/iobroker/node_modules/iobroker.rainbird/main.js:134:13)
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at RainbirdController.getModelAndVersion (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:422:10)
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at RainbirdController.processCommand (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:367:7)
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at RainbirdController.processQueue (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:385:7)
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at RainbirdController.command (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:323:10)
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at RainbirdController.request (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:173:15)
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:326:25
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:390:27
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: at Object.callback (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:424:28)
host.iobroker | 2020-02-24 21:30:50.094 | error | Caught by controller[0]: TypeError: Cannot read property 'modelID' of undefined
rainbird.0 | 2020-02-24 21:30:49.582 | info | (14607) Terminated (NO_ERROR): Without reason
rainbird.0 | 2020-02-24 21:30:49.581 | info | (14607) terminating
rainbird.0 | 2020-02-24 21:30:49.575 | error | at main (/opt/iobroker/node_modules/iobroker.rainbird/main.js:124:2)
rainbird.0 | 2020-02-24 21:30:49.575 | error | at pollStates (/opt/iobroker/node_modules/iobroker.rainbird/main.js:134:13)
rainbird.0 | 2020-02-24 21:30:49.575 | error | at RainbirdController.getModelAndVersion (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:422:10)
rainbird.0 | 2020-02-24 21:30:49.575 | error | at RainbirdController.processCommand (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:367:7)
rainbird.0 | 2020-02-24 21:30:49.575 | error | at RainbirdController.processQueue (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:385:7)
rainbird.0 | 2020-02-24 21:30:49.575 | error | at RainbirdController.command (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:323:10)
rainbird.0 | 2020-02-24 21:30:49.575 | error | at RainbirdController.request (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:173:15)
rainbird.0 | 2020-02-24 21:30:49.575 | error | at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:326:25
rainbird.0 | 2020-02-24 21:30:49.575 | error | at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:390:27
rainbird.0 | 2020-02-24 21:30:49.575 | error | at Object.callback (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:424:28)
rainbird.0 | 2020-02-24 21:30:49.575 | error | (14607) TypeError: Cannot read property 'modelID' of undefined
rainbird.0 | 2020-02-24 21:30:49.575 | error | (14607) uncaught exception: Cannot read property 'modelID' of undefined
rainbird.0 | 2020-02-24 21:30:49.568 | warn | (14607) Error in request from client for ModelAndVersion: {}
rainbird.0 | 2020-02-24 21:30:49.568 | info | (14607) Exception on request: [{},{"url":"http:// 192.168.178.113/stick","method":"POST","agent":{"_events":{},"_eventsCount":1,"_maxListeners":100,"defaultPort":80,"protocol":"http:","options":{"tim
rainbird.0 | 2020-02-24 21:30:49.567 | warn | (14607) Error in request from client for ModelAndVersion: {}
rainbird.0 | 2020-02-24 21:30:49.567 | warn | (14607) Request reply error: [{},null,null]
rainbird.0 | 2020-02-24 21:30:49.558 | info | (14607) [INFO] Configured polling interval: 20000
rainbird.0 | 2020-02-24 21:30:49.553 | info | (14607) [START] Starting Rain Bird adapter
rainbird.0 | 2020-02-24 21:30:49.541 | info | (14607) starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.rainbird, node: v10.19.0

`

I run ioBroker in a docker.
I guess i need to forward some ports but am not sure which ones.

Bin für jegliche Hilfe dankbar! ;-)

**Comment by StrathCole** [comment]
The requests are made via port 80 and sometimes possibly port 443. Those have to be reachable at the target ip originating from the docker container.

**Comment by Schorlewalker** [comment]
I tested outside of the docker environment, on a new clean pi iobroker and it does not work. :-(


host.Raspberry-Telefontisch | 2020-03-14 23:24:01.463 | info | Restart adapter system.adapter.rainbird.0 because enabled
-- | -- | -- | --
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.463 | info | instance system.adapter.rainbird.0 terminated with code 0 (NO_ERROR)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.463 | error | Caught by controller[0]: at main (/opt/iobroker/node_modules/iobroker.rainbird/main.js:124:2)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.462 | error | Caught by controller[0]: at pollStates (/opt/iobroker/node_modules/iobroker.rainbird/main.js:134:13)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.461 | error | Caught by controller[0]: at RainbirdController.getModelAndVersion (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:422:10)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.461 | error | Caught by controller[0]: at RainbirdController.processCommand (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:367:7)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.461 | error | Caught by controller[0]: at RainbirdController.processQueue (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:385:7)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.461 | error | Caught by controller[0]: at RainbirdController.command (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:323:10)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.460 | error | Caught by controller[0]: at RainbirdController.request (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:173:15)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.460 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:326:25
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.460 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:390:27
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.459 | error | Caught by controller[0]: at Object.callback (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:424:28)
host.Raspberry-Telefontisch | 2020-03-14 23:24:01.459 | error | Caught by controller[0]: TypeError: Cannot read property 'modelID' of undefined
rainbird.0 | 2020-03-14 23:24:00.945 | info | (1519) Terminated (NO_ERROR): Without reason
rainbird.0 | 2020-03-14 23:24:00.943 | info | (1519) terminating
rainbird.0 | 2020-03-14 23:24:00.925 | error | (1519) TypeError: Cannot read property 'modelID' of undefined at Object.callback (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:424:28) at /opt/iobroker/node_modules/iobroker.ra
rainbird.0 | 2020-03-14 23:24:00.924 | error | (1519) uncaught exception: Cannot read property 'modelID' of undefined
rainbird.0 | 2020-03-14 23:24:00.905 | warn | (1519) Error in request from client for ModelAndVersion: {}
rainbird.0 | 2020-03-14 23:24:00.905 | info | (1519) Exception on request: [{},{"url":"http:// 192.168.178.113/stick","method":"POST","agent":{"_events":{},"_eventsCount":1,"_maxListeners":100,"defaultPort":80,"protocol":"http:","options":{"timeo
rainbird.0 | 2020-03-14 23:24:00.904 | warn | (1519) Error in request from client for ModelAndVersion: {}
rainbird.0 | 2020-03-14 23:24:00.903 | warn | (1519) Request reply error: [{},null,null]
rainbird.0 | 2020-03-14 23:24:00.885 | info | (1519) [INFO] Configured polling interval: 20000
rainbird.0 | 2020-03-14 23:24:00.871 | info | (1519) [START] Starting Rain Bird adapter
rainbird.0 | 2020-03-14 23:24:00.820 | info | (1519) starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.rainbird, node: v10.19.0
host.Raspberry-Telefontisch | 2020-03-14 23:23:58.690 | info | instance system.adapter.rainbird.0 started with pid 1519
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.671 | info | Restart adapter system.adapter.rainbird.0 because enabled
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.670 | info | instance system.adapter.rainbird.0 terminated with code 0 (NO_ERROR)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.669 | error | Caught by controller[0]: at main (/opt/iobroker/node_modules/iobroker.rainbird/main.js:124:2)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.668 | error | Caught by controller[0]: at pollStates (/opt/iobroker/node_modules/iobroker.rainbird/main.js:134:13)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.668 | error | Caught by controller[0]: at RainbirdController.getModelAndVersion (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:422:10)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.667 | error | Caught by controller[0]: at RainbirdController.processCommand (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:367:7)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.666 | error | Caught by controller[0]: at RainbirdController.processQueue (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:385:7)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.666 | error | Caught by controller[0]: at RainbirdController.command (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:323:10)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.665 | error | Caught by controller[0]: at RainbirdController.request (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:173:15)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.665 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:326:25
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.664 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:390:27
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.663 | error | Caught by controller[0]: at Object.callback (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:424:28)
host.Raspberry-Telefontisch | 2020-03-14 23:23:28.662 | error | Caught by controller[0]: TypeError: Cannot read property 'modelID' of undefined
rainbird.0 | 2020-03-14 23:23:28.128 | info | (1502) Terminated (NO_ERROR): Without reason
rainbird.0 | 2020-03-14 23:23:28.127 | info | (1502) terminating
rainbird.0 | 2020-03-14 23:23:28.098 | error | at main (/opt/iobroker/node_modules/iobroker.rainbird/main.js:124:2)
rainbird.0 | 2020-03-14 23:23:28.098 | error | at pollStates (/opt/iobroker/node_modules/iobroker.rainbird/main.js:134:13)
rainbird.0 | 2020-03-14 23:23:28.098 | error | at RainbirdController.getModelAndVersion (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:422:10)
rainbird.0 | 2020-03-14 23:23:28.098 | error | at RainbirdController.processCommand (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:367:7)
rainbird.0 | 2020-03-14 23:23:28.098 | error | at RainbirdController.processQueue (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:385:7)
rainbird.0 | 2020-03-14 23:23:28.098 | error | at RainbirdController.command (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:323:10)
rainbird.0 | 2020-03-14 23:23:28.098 | error | at RainbirdController.request (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:173:15)
rainbird.0 | 2020-03-14 23:23:28.098 | error | at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:326:25
rainbird.0 | 2020-03-14 23:23:28.098 | error | at /opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:390:27
rainbird.0 | 2020-03-14 23:23:28.098 | error | at Object.callback (/opt/iobroker/node_modules/iobroker.rainbird/lib/rainbird.js:424:28)
rainbird.0 | 2020-03-14 23:23:28.098 | error | (1502) TypeError: Cannot read property 'modelID' of undefined
rainbird.0 | 2020-03-14 23:23:28.098 | error | (1502) uncaught exception: Cannot read property 'modelID' of undefined
rainbird.0 | 2020-03-14 23:23:28.079 | warn | (1502) Error in request from client for ModelAndVersion: {}
rainbird.0 | 2020-03-14 23:23:28.078 | info | (1502) Exception on request: [{},{"url":"http:// 192.168.178.113/stick","method":"POST","agent":{"_events":{},"_eventsCount":1,"_maxListeners":100,"defaultPort":80,"protocol":"http:","options":{"time
rainbird.0 | 2020-03-14 23:23:28.076 | warn | (1502) Error in request from client for ModelAndVersion: {}
rainbird.0 | 2020-03-14 23:23:28.075 | warn | (1502) Request reply error: [{},null,null]
rainbird.0 | 2020-03-14 23:23:28.054 | info | (1502) [INFO] Configured polling interval: 20000
rainbird.0 | 2020-03-14 23:23:28.041 | info | (1502) [START] Starting Rain Bird adapter
rainbird.0 | 2020-03-14 23:23:28.014 | info | (1502) starting. Version 0.1.2 in /opt/iobroker/node_modules/iobroker.rainbird, node: v10.19.0
host.Raspberry-Telefontisch | 2020-03-14 23:23:25.967 | info | instance system.adapter.rainbird.0 started with pid 1502
host.Raspberry-Telefontisch | 2020-03-14 23:23:25.944 | info | "system.adapter.rainbird.0" enabled
host.Raspberry-Telefontisch | 2020-03-14 23:22:11.997 | info | Update repository "latest" under "http://download.iobroker.net/sources-dist-latest.json"
info.0 | 2020-03-14 23:21:19.389 | info | (888) Popup news was read...
info.0 | 2020-03-14 23:21:16.665 | info | (888) starting. Version 1.5.7 in /opt/iobroker/node_modules/iobroker.info, node: v10.19.0



NO idea what the problem could be.
