### ISSUE TITLE
Adapter quite often offline

### ISSUE THREAD

**Issue by samoht0403** [StrathCole/ioBroker.rainbird#13]
Dear all,

I like the adapter but I have an issue with its connection: the adapter quite often looses the connection, so I wrote a script that reboots it. Works medium-good.

Am I the only one with this topic, have you incurred similar behavior an/or a hint for me?

Thanks in advance,
Thomas

**Comment by Feuer-sturm** [comment]
Hello @samoht0403 
which adapter version is installed?
Whar are the log files which indicates that the connection is lost?
Do you have parallel access with your handy app and ioBroker when ioBroker looses the connection to your rainbird station?

**Comment by samoht0403** [comment]
Good morning @Feuer-sturm.

Installed version is: v0.2.2
I hope it's ok to send the screenshot of the error:
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/76264476/176848881-5b42489c-6ec1-4032-8f48-cb3b1435462b.png">
I do not use the app when the error occurs.

**Comment by Feuer-sturm** [comment]
@samoht0403 I installed a long time ago the version 0.2.3 which is available on github.
Perhaps (!) this version solves your problem.

**Comment by samoht0403** [comment]
@Feuer-sturm thanks for your reply. I don't know yet where to find this. Can you give me a hint where to start? Thanks again in advance.

**Comment by Feuer-sturm** [comment]
@samoht0403 

**Please note** 
Normally github installation shall only be done if the developer tell you for testing purpose. I don't know which impact the chages had between the time when I installed from github and now.
It is always good to make and have a backup from your system :-)


To install a adapter from github do the following steps:
- activate expert mode
- Adapter menu -> Icon github cat
- Select gibthub tab and choose rainbird.
![grafik](https://user-images.githubusercontent.com/25422320/176953942-b2aa6b4b-e04f-4506-8f4e-037d6899b115.png)

**Comment by samoht0403** [comment]
You're great. I noticed you asked strathole to move it to Beta repository. Maybe I'll wait, maybe I'll give it a try. Thanks so much for your effort!

**Comment by Feuer-sturm** [comment]
you're welcome

**Comment by samoht0403** [comment]
Seems to be fixed. Consider the topic to be solved. 

Danke @Feuer-sturm!

**Comment by Feuer-sturm** [comment]
@samoht0403 great. If there is no open point you can close this issue.
